name: Ejecutar migraciones de base de datos

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: obligatorio
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Esperar a que MySQL inicie
        run: sleep 30

      - name: Ejecutar script SQL
        run: |
          sudo apt-get install -y mysql-client
          mysql -h 127.0.0.1 -P 3306 -u root -proot obligatorio < ./migrations/01-creacion.sql
